```{r}
vignette("censobr")
```
```{r}
use_suggested_pkgs <- c((requireNamespace("scales")), 
                        (requireNamespace("ggplot2")), 
                        (requireNamespace("geobr")))

use_suggested_pkgs <- all(use_suggested_pkgs)
```

```{r}
library(censobr)
```
```{r}
install.packages("geobr")
```

```{r}
library(arrow)
library(dplyr)
library(geobr)
library(ggplot2)
```

```{r}
# download data
tract_basico <- read_tracts(year = 2010,
                            dataset = "Basico", 
                            showProgress = FALSE)

tract_income <- read_tracts(year = 2010,
                            dataset = "DomicilioRenda", 
                            showProgress = FALSE)

# select columns
tract_basico <- tract_basico |> select('code_tract','V002')
tract_income <- tract_income |> select('code_tract','V003')

# merge
tracts_df <- left_join(tract_basico, tract_income) |> collect()

# calculate income per capita
tracts_df <- tracts_df |> mutate(income_pc = V003 / V002)
head(tracts_df)
```


```{r}
library(geobr)
tracts = read_census_tract(code_tract = "all", year=2010)
```

```{r}
# Now I'll be trying to get the population, average income and income per capita for each seller and buyer location in my full_df. First I need to load the census tract data from 2010

# Load demographic and income data

tract_basico = read_tracts(year = 2010, dataset = "Basico", showProgress = FALSE)

tract_income = read_tracts(year = 2010, dataset = "DomicilioRenda", showProgress = FALSE)

```

```{r}
# Load my dataframe of Olist data
full_df <- readRDS("C:\\Users\\willf\\OneDrive\\Documents\\NYDSA\\R\\Olist\\Data\\RDS_DFs\\full_df.rds")

```

```{r}
# Convert full_df locations into spatial objects

library(dplyr)
library(sf)

# filter out na rows for customer and seller lon/lat

customer_locations = full_df %>%
  filter(!is.na(customer_longitude) & !is.na(customer_latitude)) %>%
  st_as_sf(coords = c("customer_longitude", "customer_latitude"), crs = 4326)

seller_locations = full_df %>%
  filter(!is.na(seller_longitude) & !is.na(seller_latitude)) %>%
  st_as_sf(coords = c("seller_longitude",
                               "seller_latitude"), crs = 4326)
```
```{r}
st_crs(customer_locations)
st_crs(tracts)
```
```{r}
# Transform geolocations to matching formats
customer_locations = st_transform(customer_locations, crs = 4674)
seller_locations = st_transform(seller_locations, crs = 4674)
```
```{r}
# Remove any errors
tracts = st_make_valid((tracts))
```

```{r}
# Join tracts with locations
customer_tracts = st_join(customer_locations, tracts)
seller_tracts = st_join(seller_locations, tracts)

```

```{r}
saveRDS(customer_tracts, "customer_tracts.rds")
saveRDS(seller_tracts, "seller_tracts.rds")
```


```{r}
str(full_df$seller_id)
str(seller_tracts$seller_id)
```
```{r}
sum(is.na(full_df$seller_id))
sum(is.na(seller_tracts$seller_id))
```
```{r}
# Check column names and data types troubleshooting the merging on seller_id

any(duplicated(seller_tracts$seller_id))
```
```{r}
# Get rid of all order rows in the seller and customer tracts DFs because they cause multiple seller and customer ids which prohibits the join.

seller_tracts_simple = seller_tracts %>%
  select(seller_id, code_tract, zone, code_muni, name_muni, name_neighborhood, code_neighborhood, code_subdistrict, name_subdistrict, code_district, name_district, code_state, geometry) %>%
  distinct()

customer_tracts_simple = customer_tracts %>%
  select(customer_id, code_tract, zone, code_muni, name_muni, name_neighborhood, code_neighborhood, code_subdistrict, name_subdistrict, code_district, name_district, code_state, geometry) %>%
  distinct()
```

```{r}
colnames(seller_tracts_simple)
```

```{r}
# Rename cols to differentiate seller from customer geo data

cols_to_rename = setdiff(colnames(seller_tracts_simple), "seller_id")
seller_tracts_simple = seller_tracts_simple %>%
  rename_with(~paste("sell", ., sep="_"),all_of(cols_to_rename))

cols_to_rename = setdiff(colnames(customer_tracts_simple), "customer_id")
customer_tracts_simple = customer_tracts_simple %>%
  rename_with(~paste("cust", ., sep = "_"), all_of(cols_to_rename))

```

```{r}
# Fill NAs and then Merge joined tracts into DF

full_df$seller_id[is.na(full_df$seller_id)] = "NA_placeholder"
full_df$customer_id[is.na(full_df$customer_id)] = "NA_placeholder"

full_df_joined = full_df %>%
  left_join(customer_tracts_simple, by = "customer_id") %>%
  left_join(seller_tracts_simple, by = "seller_id")

```
```{r}
str(full_df_joined)
```


```{r}
# Now working to add population, income and income per capita to full_df

library(censobr)
library(dplyr)

# download data
tract_basico = read_tracts(year = 2010, dataset = "Basico", showProgress = FALSE)
tract_income = read_tracts(year = 2010, dataset = "DomicilioRenda", showProgress = FALSE)

# select the columns
tract_basico = tract_basico %>% select (code_tract, V002) #V002 is populaltion

tract_income = tract_income %>% select(code_tract, V003) #VOO3 is income

# Merge and calc per capita income
tracts_percap = left_join(tract_basico, tract_income, by = "code_tract") %>%
                            mutate(income_pc = V003 / V002)

```
```{r}
# Merge income, pop and income pc into full_df_joined

#First convert tracts percap to standard df

tracts_percap = as.data.frame(tracts_percap)

# Join customer data 

full_censo_df = full_df_joined %>%
  left_join(tracts_percap, by = c("cust_code_tract" = "code_tract")) %>% 
  rename_with(~paste("cust", ., sep = "_"), starts_with("V002")) %>%
  rename_with(~paste("cust", ., sep = "_"), starts_with("V003")) %>%
  rename_with(~paste("cust", ., sep = "_"), starts_with("income_pc"))
            
# Join seller data

full_censo_df = full_censo_df %>%
  left_join(tracts_percap, by = c("sell_code_tract" =  "code_tract")) %>%
  rename_with(~paste("sell", ., sep = "_"), starts_with("V002")) %>%
  rename_with(~paste("sell", ., sep = "_"), starts_with("V003")) %>%
  rename_with(~paste("sell", ., sep = "_"), starts_with("income_pc"))
```

```{r}
str(full_censo_df)
```


```{r}
# Now run checks on full_censo_df to make sure merged properly
str(full_censo_df)

summary(full_censo_df)

```

```{r}
# Run check to see if full_df col NAs and full_censo_df col NAs match

# ID matching columns 
matching_columns = intersect(colnames(full_df), colnames(full_censo_df))

# Count NAs per column func
count_nas = function(df,columns) {
  sapply(df[columns], function(col) sum(is.na(col)))
}

# Count NAs per column
nas_full_df = count_nas(full_df, matching_columns)
nas_full_censo_df = count_nas(full_censo_df, matching_columns)

# Compare col na counts
na_comparison = data.frame(
  Column = matching_columns,
  NAs_in_full = nas_full_df, 
  NAs_in_full_censo = nas_full_censo_df
)

na_comparison
```
```{r}
# Check for duplications

full_censo_dupes = full_censo_df[duplicated(full_censo_df),]
num_duplicates = nrow(full_censo_dupes)
print(num_duplicates)

```
```{r}
# Since many rows are nearly dupes except for payment sequential and payment value, checking if these are the only fields that make many rows unique

other_cols = setdiff(names(full_censo_df), c("payment_sequential", "payment_value"))
print(other_cols)


```
```{r}
l;kh;
```

```{r}
saveRDS(full_censo_df, "C:\\Users\\willf\\OneDrive\\Documents\\NYDSA\\R\\Olist\\Data\\full_censo_df.rds" )

write.csv(full_censo_df, "C:\\Users\\willf\\OneDrive\\Documents\\NYDSA\\R\\Olist\\Data\\full_censo_df.csv", row.names = FALSE)
```

