Test muni_map_df leaflet maps
```{r}
library(leaflet)
library(dplyr)
library(sf)
library(RColorBrewer)

# muni_map_sf = readRDS("..//Data//muni_map_sf")
# muni_map_sf <- st_as_sf(muni_map_df)

muni_map_sf <- st_transform(muni_map_sf, crs = 4326)

# filter out geometry collections
muni_map_sf <- muni_map_sf %>%
  filter(st_geometry_type(muni_geom) != "GEOMETRYCOLLECTION")

# Transform log of total LTV
muni_map_sf$total_seller_LTV_log <- log(muni_map_sf$total_seller_LTV + 1)

palette_log <- colorNumeric(palette = "viridis", domain = muni_map_sf$total_seller_LTV_log)

leaflet(muni_map_sf) %>%
  addTiles() %>%
  addPolygons(fillColor = ~palette_log(total_seller_LTV_log),
              weight = 0,
              opacity = 1,
              color = "transparent",
              dashArray = "3",
              fillOpacity = 0.7,
              label = ~paste(muni_name, "LTV:", total_seller_LTV),
              highlight = highlightOptions(weight = 5,
                                            color = "#666",
                                            dashArray = "",
                                            fillOpacity = 0.7,
                                            bringToFront = TRUE),
              labelOptions = labelOptions(style = list("font-weight" = "normal"),
                                          textsize = "13px",
                                          direction = "auto")) %>%
  addLegend(pal = palette_log, values = ~total_seller_LTV_log,
            opacity = 0.7, title = "Total Seller LTV (log)")

```


```{r}
zip_map_df$total_seller_LTV_log <- log(zip_map_df$total_seller_LTV + 1)


# Create the color palette
palette <- colorNumeric(palette = "viridis", domain = zip_map_df$total_seller_LTV_log)

# Select representative breaks in the original scale
breaks_orig <- c(100, 500, 1000, 5000, 10000) # Adjust these values based on your data range
labels_orig <- as.character(breaks_orig) # Create labels from these breaks

# Map these breaks to the log scale for coloring
breaks_log <- log(breaks_orig + 1)

# Create color palette
palette <- colorNumeric(palette = "viridis", domain = breaks_log)

# Create Leaflet map
leaflet(zip_map_df) %>%
  addTiles() %>%
  addCircleMarkers(
    lng = ~longitude, 
    lat = ~latitude,
    fillColor = ~palette(log(total_seller_LTV + 1)),
    color = "transparent",
    fillOpacity = 0.7,
    radius = 5,
    popup = ~paste(seller_zip, "LTV:", total_seller_LTV)
  ) %>%
  addLegend(
    position = "bottomright",
    title = "Total Seller LTV",
    colors = palette(breaks_log),
    labels = labels_orig
  )
```


```{r}
library(ggplot2)

ggplot(zip_map_df, aes(x = seller_zip_incomepc, y = total_seller_LTV)) +
  geom_point() +
  labs(x = "Seller Zip Income per Capita", y = "Total Seller LTV", 
       title = "Scatter Plot of Seller Zip Income per Capita vs Total Seller LTV") +
  theme_minimal()


```

```{r}
# Create csv with no geometry

muni_map_exgeom = subset(muni_map_df, select = -muni_geom)

write.csv(muni_map_exgeom, "..//Data//muni_map_exgeom.csv")
```


```{r}
zip_map_exgeom = subset(zip_map_df, select = -zip_point)

write.csv(zip_map_exgeom, "..//Data//zip_map_exgeom.csv")
```

```{r}
muni_map_cut = muni_map_exgeom %>%
  select(muni_population, avg_price_per_seller, total_sales, avg_review_score_per_seller, total_seller_LTV)

write.csv(muni_map_cut, "..//Data//muni_map_cut.csv")
```

```{r}
# Load necessary library
library(scales)

# Creating a histogram for the 'total_sales' column in the 'muni_map_sf' dataframe
ggplot(muni_map_sf, aes(x = total_sellers)) +
  geom_histogram(binwidth = 2,  # Adjust binwidth as needed for your data
                 fill = "blue", 
                 color = "black") +
  theme_minimal() +
  scale_x_continuous(labels = label_comma()) +  # Format x-axis labels with commas
  labs(title = "Histogram of Total Sales in Municipalities",
       x = "Total Sales",
       y = "Frequency")

```


```{r}
summary(muni_map_sf)
```

```{r}
unique(st_geometry_type(muni_map_sf))

```

